apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvwa-mysql-data
  namespace: dvwa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
